# Generated by Django 5.0 on 2024-01-14 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_rename_couser_activity_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='Losson',
            new_name='lesson',
        ),
    ]
