# Generated by Django 5.0 on 2024-01-14 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_rename_losson_activity_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
